[package]
name = "bridge_view_server"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.9"
bridge_view_protocol = { path = "../protocol" }
screencapturekit = "1.2.0"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
